DROP OWNED BY nuadmin;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA nusoft FROM nuadmin;

DROP USER IF EXISTS nuadmin;
CREATE USER nuadmin WITH PASSWORD 'nuadmin'
CREATE SCHEMA IF NOT EXISTS nusoft AUTHORIZATION nuadmin;
